project:
  type: website
  resources:
    - CNAME
    - dashboard/  

website:
  site-url: http://i-shchapov.github.io
  title: "Ivan Shchapov"
  twitter-card:
    creator: "@ShchapovEcon"
    description: "Ivan Shchapov, Ph.D. candidate at Institut Polytechnique de Paris working on monetary macroeconomics and financial frictions"
    image: resources/Headshot.jpg
    card-style: summary
  open-graph: true
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV
      - href: dashboard/phd_job_market_dashboard_ivan.html
        text: Job Market Dashboard
    tools:
      - icon: filetype-pdf
        text: CV [PDF]
        href: resources/cv.pdf
      - icon: github
        text: Github
        href: https://github.com/i-shchapov   
  back-to-top-navigation: true
  google-analytics: "G-VL29ZRQXB3"
  announcement:
    icon: info-circle
    dismissable: true
    content: "I am on the Academic Job Market in November 2025"
    type: primary
    position: below-navbar
  

format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



